name: 'build-ios'
on:
  push:
    branches:
      - master
jobs:
  build-ios:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: npm install
      
      - run: cd ios && pod install

      #- name: Build app
        #run: |
          #xcodebuild -workspace ReactNativeCICD.xcworkspace -scheme ReactNativeCICD archive -archivePath ReactNativeCICD.xcarchive -allowProvisioningUpdates
          #xcodebuild -exportArchive -archivePath ./ReactNativeCICD.xcarchive -exportPath . -exportOptionsPlist ReactNativeCICD/Info.plist
          #mv ReactNativeCICD.ipa ../ReactNativeCICD.ipa
      #- name: Upload Artifact
        #uses: actions/upload-artifact@v1
        #with:
          #name: myapReactNativeCICDp.ipa
          #path: ios/build/