name: 'build-ios'
on:
  push:
    branches:
      - master
jobs:
  build-ios:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: npm install
      
      - run: cd ios && pod install
      