name: 'e2e-android-2'
on:
  push:
    branches:
      - master
jobs:
  detox:
    name: Detox Tests
    if: false
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: |
          brew tap wix/brew
          brew install applesimutils
      - run: node node_modules/.bin/detox build --configuration android
      - run: node node_modules/.bin/detox test --configuration android --cleanup
